package handler

import (
	"context"
	"encoding/json"
	"net/http"
	"paygo-api/internal/domain"
	"time"
)

type Handlers struct {
	UserService domain.UserService
}

func NewHandlers(userService domain.UserService) *Handlers {
	return &Handlers{
		UserService: userService,
	}
}

func (h *Handlers) RegisterNewUser(w http.ResponseWriter, r *http.Request) {
	var newUser domain.RegisterUserRequest

	if err := json.NewDecoder(r.Body).Decode(&newUser); err != nil {
		http.Error(w, "Invalid request payload", http.StatusBadRequest)
		return
	}

	if newUser.Email == "" || newUser.Password == "" || newUser.FirstName == "" || newUser.LastName == "" || newUser.PhoneNumber == "" {
		http.Error(w, "All fields are required", http.StatusBadRequest)
		return
	}

	ctx, cancel := context.WithTimeout(r.Context(), 5*time.Second)
	defer cancel()

	user := domain.User{
		Email:        newUser.Email,
		PasswordHash: newUser.Password,
		Firstname:    newUser.FirstName,
		Lastname:     newUser.LastName,
		PhoneNumber:  newUser.PhoneNumber,
	}

	if err := h.UserService.Register(ctx, &user); err != nil {
		if err.Error() == "email already exists" {
			http.Error(w, err.Error(), http.StatusConflict) // 409 Conflict
			return
		}
		http.Error(w, "Internal server error", http.StatusInternalServerError) // 500
		return
	}

	response := domain.UserResponse{
		// user.PublicID was generated by Postgres and captured by RETURNING
		ID:          user.PublicID,
		Email:       user.Email,
		FirstName:   user.Firstname,
		LastName:    user.Lastname,
		PhoneNumber: user.PhoneNumber,
		// user.Status was set to 'active' by Postgres default and captured by RETURNING
		Status: user.Status,
	}

	// Stream that response object straight out to the client's phone or browser
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusCreated) // 201 Created
	json.NewEncoder(w).Encode(response)

}
